// Seleções (código ISO-2 minúsculo p/ bandeira via flagcdn). Use no cadastro de jogos.
export type Team = { name: string; code: string };

export const TEAMS: Team[] = [
  { name: "Brasil", code: "br" },
  { name: "Argentina", code: "ar" },
  { name: "França", code: "fr" },
  { name: "Inglaterra", code: "gb-eng" },
  { name: "Espanha", code: "es" },
  { name: "Portugal", code: "pt" },
  { name: "Alemanha", code: "de" },
  { name: "Países Baixos", code: "nl" },
  { name: "Itália", code: "it" },
  { name: "Bélgica", code: "be" },
  { name: "Croácia", code: "hr" },
  { name: "Uruguai", code: "uy" },
  { name: "Marrocos", code: "ma" },
  { name: "Estados Unidos", code: "us" },
  { name: "México", code: "mx" },
  { name: "Canadá", code: "ca" },
  { name: "Japão", code: "jp" },
  { name: "Coreia do Sul", code: "kr" },
  { name: "Senegal", code: "sn" },
  { name: "Suíça", code: "ch" },
  { name: "Dinamarca", code: "dk" },
  { name: "Colômbia", code: "co" },
  { name: "Equador", code: "ec" },
  { name: "Polônia", code: "pl" },
  { name: "Sérvia", code: "rs" },
  { name: "Gana", code: "gh" },
  { name: "Camarões", code: "cm" },
  { name: "Austrália", code: "au" },
  { name: "Catar", code: "qa" },
  { name: "Arábia Saudita", code: "sa" },
  { name: "Irã", code: "ir" },
  { name: "Tunísia", code: "tn" },
  { name: "Nigéria", code: "ng" },
  { name: "Egito", code: "eg" },
  { name: "Argélia", code: "dz" },
  { name: "Costa do Marfim", code: "ci" },
  { name: "Áustria", code: "at" },
  { name: "Escócia", code: "gb-sct" },
  { name: "País de Gales", code: "gb-wls" },
  { name: "Ucrânia", code: "ua" },
  { name: "Turquia", code: "tr" },
  { name: "Paraguai", code: "py" },
  { name: "Peru", code: "pe" },
  { name: "Chile", code: "cl" },
  { name: "Costa Rica", code: "cr" },
  { name: "Panamá", code: "pa" },
  { name: "Nova Zelândia", code: "nz" },
  { name: "Jordânia", code: "jo" },
  { name: "Uzbequistão", code: "uz" },
  { name: "África do Sul", code: "za" },
];

export function teamName(code: string): string {
  return TEAMS.find((t) => t.code === code)?.name ?? code;
}
